function run_signal_extraction(config)
% RUN_SIGNAL_EXTRACTION - Processes raw data to extract and organize neural signals.
%
% This function iterates through specified days and sessions for a given macaque,
% loads the raw data, applies trial rearrangement and baseline correction,
% and saves the processed data into block-specific .mat files.
%
% USAGE:
%   run_signal_extraction(config);
%
% INPUTS:
%   config - Struct. The main configuration struct generated by get_experiment_config.

    % Load session indexing and stimulus metadata
    fprintf('Loading session index from: %s\n', config.paths.session_idx);
    load(config.paths.session_idx, 'SessionIdx');
    
    sessionIdx_data = SessionIdx;
    fprintf('Loading stimulus metadata from: %s\n', config.paths.stim_info);
    stim_metadata = load(config.paths.stim_info, 'Meta_data');

    % --- Set up macaque-specific looping parameters (from original code) ---
    if strcmpi(config.common.A_B, 'A')
        L = 1; C = 5; E = 2; gg = 3;
    elseif strcmpi(config.common.A_B, 'B')
        L = 5; C = 8; E = 6; gg = 7;
    else
        error('Invalid A_B option in config.common.A_B. Must be "A" or "B".');
    end

    % --- Initialize data structures to hold processed data for all selected blocks ---
    % NOTE THE FUNCTION CALL CHANGE: We now call a function from our 'functions' package.
    processed_data_all_blocks = ssvep.initialize_block_data_structures(config.process_params.selected_blocks);
    
    % Pre-allocate cell array for tracking trial counts
    % all_session_repeat_nums = {}; 

    % --- Main Loop over Days ---
    for day_loop_idx = 1:length(config.process_params.Days)
        current_day_val = config.process_params.Days(day_loop_idx);
        fprintf('---> Processing Day: %d for %s <---\n', current_day_val, config.macaque_name);

        % Determine sessions to process for this day (logic from original code)
        if config.is_DG
            if strcmp(config.process_params.selected_blocks,'SSGnv')
                z = 6;
            elseif strcmp(config.process_params.selected_blocks,'SSGv')
                z = 8;
            else
                z = 3:5;
            end
            session_file_numbers = [sessionIdx_data{z, current_day_val}];
            u_day_prefix = sprintf('u%d', sessionIdx_data{1, current_day_val});
            raw_file_name_template = sprintf('%s2-%s-%%03d-500hz.mat', config.macaque_name, u_day_prefix);
        elseif config.is_QQ
            real_session_indices_for_day = sessionIdx_data{C, current_day_val};
            session_file_numbers = sessionIdx_data{C+1, current_day_val};
            u_day_prefix = sessionIdx_data{1, current_day_val};
            raw_file_name_template = sprintf('%s2-%s-%%03d-500hz.mat', config.macaque_name, u_day_prefix);
        end
        
        if isempty(session_file_numbers)
            fprintf('     Warning: No sessions found for day %d. Skipping.\n', current_day_val);
            continue;
        end

        % --- Inner Loop over Sessions ---
        for session_loop_idx = 1:length(session_file_numbers)
            current_session_filenum = session_file_numbers(session_loop_idx);
            fprintf('     Processing Session File: %03d\n', current_session_filenum);

            raw_data_filepath = fullfile(config.paths.raw_data_input, sprintf(raw_file_name_template, current_session_filenum));
            if ~exist(raw_data_filepath, 'file')
                fprintf('     Warning: Raw data file not found: %s. Skipping session.\n', raw_data_filepath);
                continue;
            end
            
            load(raw_data_filepath, 'Datainfo');
            
            % Determine session_factor (trial-specific metadata)
            % (This complex logic is preserved from the original)
            if config.is_DG
                metadata_day_idx = find(strcmp({stim_metadata.Meta_data{:,gg}}, u_day_prefix));
                if strcmp(config.process_params.selected_blocks,'SSGnv')
                    pp = length([SessionIdx{3:5,current_day_val}]);
                    original_session_factor = stim_metadata.Meta_data{metadata_day_idx(session_loop_idx+pp),L};
                elseif strcmp(config.process_params.selected_blocks,'SSGv')
                    pp = length([SessionIdx{3:6,current_day_val}]);
                    original_session_factor = stim_metadata.Meta_data{metadata_day_idx(session_loop_idx+pp),L};
                else
                    original_session_factor = stim_metadata.Meta_data{metadata_day_idx(session_loop_idx),L};
                end
            elseif config.is_QQ
                current_real_session_num = real_session_indices_for_day(session_loop_idx);
                stim_lookup_key = sessionIdx_data{3, current_day_val};
                metadata_day_idx = find(strcmp({stim_metadata.Meta_data{:,E}}, stim_lookup_key));
                original_session_factor = stim_metadata.Meta_data{metadata_day_idx(current_real_session_num),L};
            end
            
            % --- CALLING FUNCTIONS FROM THE 'functions' PACKAGE ---
            ReFactor = ssvep.IdxRearrage(Datainfo.VSinfo.sMbmInfo.respCode, original_session_factor);
            
            % Select MUA/LFP data based on config
            switch upper(config.process_params.MUA_LFP)
                case 'MUA1', neural_data_for_session = Datainfo.trial_MUA{1};
                case 'MUA2', neural_data_for_session = Datainfo.trial_MUA{2};
                case 'LFP',  neural_data_for_session = Datainfo.trial_LFP;
                otherwise, error('Invalid MUA_LFP_idx in config.');
            end

            % Process trials (rearrange, baseline, etc.)
            [~, session_clustered_data] = ssvep.TrialDataRearrange(config, ReFactor, neural_data_for_session);
            
            % Concatenate data from this session into the main data structures
            processed_data_all_blocks = ssvep.update_block_data_with_session(processed_data_all_blocks, session_clustered_data, config.process_params.selected_blocks);
        end
    end
    
    % --- Save the final processed data ---
    fprintf('---> Finalizing and saving processed data... <---\n');
    ssvep.save_processed_block_data(config, processed_data_all_blocks);
end